"""empty message

Revision ID: f49862a8fd08
Revises: 
Create Date: 2023-11-23 20:35:22.450769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49862a8fd08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nvcss_code', sa.String(length=100), nullable=False),
    sa.Column('model_no', sa.String(length=100), nullable=False),
    sa.Column('frame_no', sa.String(length=100), nullable=False),
    sa.Column('suffix', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specifications_judgement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('partname', sa.String(length=100), nullable=False),
    sa.Column('actual_specification', sa.String(length=100), nullable=False),
    sa.Column('detected_specification', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specifications_judgement')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
